import type { GanttTranslations } from './types';

/** Built-in UI dictionaries. Add a locale here; applications can still override individual keys via options.translations. */
export const BUILT_IN_TRANSLATIONS: Record<'fr' | 'en', GanttTranslations> = {
  fr: {
    import: 'Importer', exportJson: 'Exporter JSON', exportMspxml: 'Exporter MSPXML', exportMpp: 'Exporter MPP', exportMppUnavailable: 'Configurez projectFileAdapter pour le format binaire MPP', saveLocal: 'Local', loadLocal: 'Local', addTask: 'Tâche', delete: 'Supprimer', expandAll: 'Tout déplier', collapseAll: 'Tout replier', columns: 'Colonnes', search: 'Rechercher tâche ou ressource', previousResult: 'Résultat précédent', nextResult: 'Résultat suivant', zoomOut: 'Zoom arrière', zoomIn: 'Zoom avant', fitTask: 'Ajuster la tâche', fitGantt: 'Ajuster le Gantt', noTasks: 'Aucune tâche. Utilisez « ＋ Tâche » ou importez un projet.', noPlanningData: 'Aucune donnée de planning.', today: 'Aujourd’hui', resources: 'Ressources', cost: 'Coût', totalQuantity: 'Qté totale', addResource: 'Ajouter une ressource', editTask: 'Éditer la tâche', addTaskAfter: 'Ajouter une tâche après', close: 'Fermer', general: 'Général', links: 'Liens', name: 'Nom', code: 'Code', type: 'Type', color: 'Couleur', progress: 'Avancement', parent: 'Parent', root: 'Racine', start: 'Début', finish: 'Fin', task: 'Tâche', phase: 'Phase', milestone: 'Jalon', resourceCatalogue: 'Référentiel de ressources', searchResource: 'Rechercher une ressource…', searching: 'Recherche en cours…', resource: 'Ressource', add: 'Ajouter', noResourceAssigned: 'Aucune ressource affectée.', noLink: 'Aucun lien pour cette tâche.', addPredecessor: 'Ajouter un prédécesseur…', columnMenuTitle: 'Colonnes affichées', required: 'obligatoire', reset: 'Réinitialiser', mode: 'Mode', duration: 'Durée', totalCost: 'Coût total', automatic: 'Auto', manual: 'Manuel',
  },
  en: {
    import: 'Import', exportJson: 'Export JSON', exportMspxml: 'Export MSPXML', exportMpp: 'Export MPP', exportMppUnavailable: 'Configure projectFileAdapter for binary MPP files', saveLocal: 'Local', loadLocal: 'Local', addTask: 'Task', delete: 'Delete', expandAll: 'Expand all', collapseAll: 'Collapse all', columns: 'Columns', search: 'Search tasks or resources', previousResult: 'Previous result', nextResult: 'Next result', zoomOut: 'Zoom out', zoomIn: 'Zoom in', fitTask: 'Fit task', fitGantt: 'Fit Gantt', noTasks: 'No tasks. Use “＋ Task” or import a project.', noPlanningData: 'No planning data.', today: 'Today', resources: 'Resources', cost: 'Cost', totalQuantity: 'Total quantity', addResource: 'Add resource', editTask: 'Edit task', addTaskAfter: 'Add task after', close: 'Close', general: 'General', links: 'Links', name: 'Name', code: 'Code', type: 'Type', color: 'Color', progress: 'Progress', parent: 'Parent', root: 'Root', start: 'Start', finish: 'Finish', task: 'Task', phase: 'Phase', milestone: 'Milestone', resourceCatalogue: 'Resource catalogue', searchResource: 'Search a resource…', searching: 'Searching…', resource: 'Resource', add: 'Add', noResourceAssigned: 'No resource assigned.', noLink: 'No link for this task.', addPredecessor: 'Add predecessor…', columnMenuTitle: 'Visible columns', required: 'required', reset: 'Reset', mode: 'Mode', duration: 'Duration', totalCost: 'Total cost', automatic: 'Auto', manual: 'Manual',
  },
};

/** Selects a built-in dictionary from an IETF locale such as `fr-FR` or `en-GB`. */
export function getBuiltInTranslations(locale: string): GanttTranslations {
  return locale.toLowerCase().startsWith('fr') ? BUILT_IN_TRANSLATIONS.fr : BUILT_IN_TRANSLATIONS.en;
}
